# Taps
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"

# Make sure apps get installed in system Applications dir
cask_args appdir: '/Applications'

# Install ZSH
brew 'zsh'

# Install GNU core utilities (those that come with MacOS are outdated)
brew 'coreutils'

# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
brew 'findutils'

# Build tools
brew "autoconf"
brew "automake"

# Install Binaries
brew 'bash'
brew 'curl'
brew 'eza'
brew 'fzf'
brew 'git'
brew 'git-cliff'
brew 'git-delta'
brew "ggrep"
brew "gh"
brew 'glab'
brew 'htop'
brew 'jandedobbeleer/oh-my-posh/oh-my-posh'
brew 'jq'
brew 'lazygit'
brew 'nano'
brew 'neovim'
brew 'nss'
brew 'openssl'
brew 'pygments'
brew 'ripgrep'
brew 'rsync'
brew 'rtx'
brew 'scrcpy'
brew 'termapps/tap/enquirer' # for `mr` command
brew 'tmux'
brew 'trash'
brew 'watch'
brew 'wget'
brew 'yt-dlp'
brew 'z'

# Install backend development stuff
brew 'dive'
brew 'hadolint'
brew 'mkcert'

# Install frontend development stuff
brew 'volta'

# Fonts
cask 'font-jetbrains-mono'
cask 'font-jetbrains-mono-nerd-font'

# Apps
cask '1password'
cask '1password-cli'
cask 'appcleaner'
cask 'bettertouchtool'
cask 'bluesnooze'
cask 'calibre'
cask 'docker'
cask 'firefox'
cask 'firefox-developer-edition'
cask 'fork'
cask 'google-chrome'
cask 'google-drive'
cask 'itsycal'
cask 'jetbrains-toolbox'
cask 'kitty'
cask 'postman'
cask 'rar'
cask "raycast"
cask 'slack'
cask 'spotify'
cask 'telegram'
cask 'ticktick'
cask 'visual-studio-code'
cask 'vlc'
cask 'whatsapp'
