# Taps
tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/services"
tap "homebrew/cask-fonts"

# Make sure apps get installed in system Applications dir
cask_args appdir: '/Applications'

# Install ZSH
brew 'zsh'
brew 'zsh-completions'
brew 'zsh-git-prompt'
brew 'zsh-syntax-highlighting'

# Install GNU core utilities (those that come with OS X are outdated)
brew 'coreutils'

# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
brew 'findutils'

# Install Binaries
brew 'diff-so-fancy'
brew 'git'
brew 'htop'
brew 'hub'
brew 'zaquestion/tap/lab'
brew 'mkcert'
brew 'nano'
brew 'nss'
brew 'openssl'
brew "redis", restart_service: true
brew 'rbenv'
brew 'ruby-build'
brew 'scrcpy'
brew 'watch'
brew 'wget'
brew 'whois'
brew 'youtube-dl'

# Install Frontend stuff
brew 'node'
brew 'yarn'

# Fonts
cask 'font-fira-code'
cask 'font-jetbrains-mono'

# Apps
cask '1password'
cask 'alfred'
cask 'appcleaner'
cask 'bettertouchtool'
cask 'boostnote'
cask 'docker'
cask 'fork'
cask 'google-backup-and-sync'
cask 'google-chrome'
cask 'iina'
cask 'iterm2'
cask 'itsycal'
cask 'jetbrains-toolbox'
cask 'slack'
cask 'spotify'
cask 'java'
cask 'flux'
cask 'visual-studio-code'
cask 'whatsapp'

# Quicklook
cask 'qlcolorcode'
cask 'qlmarkdown'
cask 'quicklook-csv'
cask 'qlstephen'
