#!/bin/bash
code --install-extension Angular.ng-template
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension PKief.material-icon-theme
code --install-extension WallabyJs.quokka-vscode
code --install-extension christian-kohler.path-intellisense
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension eg2.tslint
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension felixfbecker.php-intellisense
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension k--kato.intellij-idea-keybindings
code --install-extension leizongmin.node-module-intellisense
code --install-extension mikestead.dotenv
code --install-extension mrmlnc.vscode-scss
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension octref.vetur
code --install-extension rbbit.typescript-hero
code --install-extension robertohuertasm.vscode-icons
code --install-extension robinbentley.sass-indented
code --install-extension steoates.autoimport
code --install-extension xabikos.ReactSnippets